-- THÊM CỘT public_code (đuôi pr{số} ổn định cho URL sản phẩm)
-- Chạy trong Supabase Dashboard SQL Editor. An toàn chạy lại (idempotent).
--
-- Ý tưởng: public_code là số nguyên ổn định, độc lập tiêu đề/khu vực. URL sản phẩm
-- mới dạng /{lt}/{areaSlug}/{districtSlug?}/{slug}-pr{public_code}. Đổi tiêu đề/slug
-- KHÔNG đổi public_code → link không vỡ, chỉ 301 về canonical mới nhất.

BEGIN;

-- 0) Soi trước: tổng tin + đã có cột chưa
SELECT count(*) AS tong_tin FROM properties;

-- 1) Thêm cột (nếu chưa có) — chưa gắn IDENTITY để backfill trước
ALTER TABLE properties ADD COLUMN IF NOT EXISTS public_code bigint;

-- 2) Backfill tin cũ chưa có code: đánh số từ 1000 theo created_at (cũ → mới).
--    Chỉ gán cho dòng đang NULL nên chạy lại không đè số đã có.
WITH ranked AS (
  SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn
  FROM properties
  WHERE public_code IS NULL
)
UPDATE properties p
SET public_code = 999 + r.rn
FROM ranked r
WHERE p.id = r.id;

-- 3) Ràng buộc UNIQUE (nếu chưa có)
CREATE UNIQUE INDEX IF NOT EXISTS idx_properties_public_code ON properties (public_code);

-- 4) NOT NULL (bắt buộc trước khi gắn IDENTITY). An toàn vì bước 2 đã backfill mọi dòng.
ALTER TABLE properties ALTER COLUMN public_code SET NOT NULL;

-- 5) Gắn IDENTITY cho tin mới, START WITH = max hiện tại + 1.
--    Bọc DO để tính START động + bỏ qua nếu cột đã là IDENTITY (chạy lại an toàn).
DO $$
DECLARE
  next_val bigint;
  is_identity_already text;
BEGIN
  SELECT is_identity INTO is_identity_already
  FROM information_schema.columns
  WHERE table_name = 'properties' AND column_name = 'public_code';

  IF is_identity_already = 'NO' THEN
    SELECT COALESCE(max(public_code), 999) + 1 INTO next_val FROM properties;
    EXECUTE format(
      'ALTER TABLE properties ALTER COLUMN public_code ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
      next_val
    );
  END IF;
END $$;

-- 6) Kiểm tra sau: mọi tin có code, không trùng
SELECT
  count(*) AS tong,
  count(public_code) AS co_code,
  count(DISTINCT public_code) AS code_duy_nhat,
  min(public_code) AS min_code,
  max(public_code) AS max_code
FROM properties;

-- 7) Xem thử vài dòng
SELECT public_code, title, created_at
FROM properties
ORDER BY public_code
LIMIT 15;

-- 8) Nạp lại schema cache của PostgREST để cột mới lộ ra API ngay
NOTIFY pgrst, 'reload schema';

COMMIT;
