-- Stable random-looking IDs for public agent profile slugs.
-- The profile UUID is generated by the database; only a short hash is exposed in the slug.
-- Production execution is user-run after read-only dry-run verification.

CREATE OR REPLACE FUNCTION public.agent_profile_slug_id(p_profile_id uuid)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
SET search_path = public, pg_temp
AS $$
  SELECT substr(md5(p_profile_id::text), 1, 8);
$$;

CREATE OR REPLACE FUNCTION public.agent_profile_slug_for_id(
  p_requested_slug text,
  p_display_name text,
  p_profile_id uuid
)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
SET search_path = public, pg_temp
AS $$
  SELECT left(
    public.slugify_agent_profile_name(
      COALESCE(NULLIF(btrim(p_requested_slug), ''), p_display_name)
    ),
    91
  ) || '-' || public.agent_profile_slug_id(p_profile_id);
$$;

CREATE OR REPLACE FUNCTION public.allocate_agent_profile_slug(
  p_requested_slug text,
  p_display_name text
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_base text;
  v_candidate text;
BEGIN
  v_base := left(
    public.slugify_agent_profile_name(
      COALESCE(NULLIF(btrim(p_requested_slug), ''), p_display_name)
    ),
    91
  );
  PERFORM pg_advisory_xact_lock(hashtextextended('agent-profile-slug:' || v_base, 0));

  LOOP
    v_candidate := v_base || '-' || substr(md5(gen_random_uuid()::text), 1, 8);
    EXIT WHEN NOT EXISTS (
      SELECT 1
      FROM public.agent_profiles ap
      WHERE ap.slug = v_candidate
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.agent_profile_slug_aliases alias_row
      WHERE alias_row.old_slug = v_candidate
    );
  END LOOP;

  RETURN v_candidate;
END;
$$;

REVOKE ALL ON FUNCTION public.agent_profile_slug_id(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.agent_profile_slug_for_id(text, text, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.allocate_agent_profile_slug(text, text) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.provision_agent_profile_from_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_display_name text := COALESCE(NULLIF(btrim(NEW.display_name), ''), 'Người đăng tin');
  v_slug text;
BEGIN
  IF NEW.role <> 'user' THEN
    UPDATE public.agent_profiles
    SET status = 'disabled', updated_at = now()
    WHERE user_id = NEW.id AND status <> 'disabled';
    RETURN NEW;
  END IF;

  v_slug := public.allocate_agent_profile_slug(NULL, v_display_name);
  INSERT INTO public.agent_profiles (
    user_id, slug, display_name, avatar_url, public_phone, status
  ) VALUES (
    NEW.id, v_slug, v_display_name, NULLIF(btrim(NEW.avatar_url), ''),
    NULLIF(btrim(NEW.phone), ''), 'published'
  )
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.save_my_agent_profile(
  p_slug text,
  p_display_name text,
  p_bio text DEFAULT NULL,
  p_avatar_url text DEFAULT NULL,
  p_public_phone text DEFAULT NULL,
  p_public_zalo text DEFAULT NULL,
  p_status text DEFAULT 'published'
)
RETURNS public.agent_profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_profile public.agent_profiles;
  v_existing_slug text;
  v_slug text;
  v_name text := btrim(p_display_name);
  v_phone text;
BEGIN
  IF v_actor IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = v_actor AND role = 'user') THEN
    RAISE EXCEPTION 'Profile not found' USING ERRCODE = '23503';
  END IF;
  IF v_name IS NULL OR length(v_name) < 1 OR length(v_name) > 120 THEN
    RAISE EXCEPTION 'Display name must be between 1 and 120 characters' USING ERRCODE = '22023';
  END IF;
  IF p_status NOT IN ('draft', 'published', 'disabled') THEN
    RAISE EXCEPTION 'Invalid agent profile status' USING ERRCODE = '22023';
  END IF;

  SELECT slug INTO v_existing_slug
  FROM public.agent_profiles
  WHERE user_id = v_actor
  FOR UPDATE;

  IF v_existing_slug IS NULL THEN
    v_slug := public.allocate_agent_profile_slug(p_slug, v_name);
  ELSIF NULLIF(btrim(p_slug), '') IS NULL THEN
    v_slug := v_existing_slug;
  ELSIF public.slugify_agent_profile_name(p_slug) = v_existing_slug THEN
    v_slug := v_existing_slug;
  ELSE
    v_slug := public.allocate_agent_profile_slug(p_slug, v_name);
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.agent_profiles
    WHERE slug = v_slug AND user_id <> v_actor
  ) OR EXISTS (
    SELECT 1
    FROM public.agent_profile_slug_aliases alias_row
    JOIN public.agent_profiles ap ON ap.id = alias_row.agent_profile_id
    WHERE alias_row.old_slug = v_slug AND ap.user_id <> v_actor
  ) THEN
    RAISE EXCEPTION 'Slug đã được sử dụng' USING ERRCODE = '23505';
  END IF;

  SELECT NULLIF(btrim(phone), '') INTO v_phone
  FROM public.profiles
  WHERE id = v_actor;

  INSERT INTO public.agent_profiles (
    user_id, slug, display_name, bio, avatar_url, public_phone, public_zalo, status, updated_at
  ) VALUES (
    v_actor, v_slug, v_name, NULLIF(btrim(p_bio), ''), NULLIF(btrim(p_avatar_url), ''),
    COALESCE(NULLIF(btrim(p_public_phone), ''), v_phone), NULLIF(btrim(p_public_zalo), ''),
    'published', now()
  )
  ON CONFLICT (user_id) DO UPDATE SET
    slug = EXCLUDED.slug,
    display_name = EXCLUDED.display_name,
    bio = EXCLUDED.bio,
    avatar_url = EXCLUDED.avatar_url,
    public_phone = EXCLUDED.public_phone,
    public_zalo = EXCLUDED.public_zalo,
    status = CASE WHEN agent_profiles.status = 'disabled' THEN 'disabled' ELSE 'published' END,
    updated_at = now()
  RETURNING * INTO v_profile;

  RETURN v_profile;
END;
$$;

CREATE OR REPLACE FUNCTION public.save_my_profile_and_agent_profile(
  p_display_name text,
  p_phone text,
  p_slug text,
  p_agent_display_name text,
  p_bio text DEFAULT NULL,
  p_public_phone text DEFAULT NULL,
  p_public_zalo text DEFAULT NULL,
  p_status text DEFAULT 'published'
)
RETURNS public.agent_profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_profile public.agent_profiles;
  v_existing_slug text;
  v_slug text;
  v_name text := btrim(p_agent_display_name);
  v_phone text := NULLIF(btrim(p_phone), '');
BEGIN
  IF v_actor IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = v_actor AND role = 'user') THEN
    RAISE EXCEPTION 'Profile not found' USING ERRCODE = '23503';
  END IF;
  IF v_name IS NULL OR length(v_name) < 1 OR length(v_name) > 120 THEN
    RAISE EXCEPTION 'Display name must be between 1 and 120 characters' USING ERRCODE = '22023';
  END IF;
  IF p_status NOT IN ('draft', 'published', 'disabled') THEN
    RAISE EXCEPTION 'Invalid agent profile status' USING ERRCODE = '22023';
  END IF;

  SELECT slug INTO v_existing_slug
  FROM public.agent_profiles
  WHERE user_id = v_actor
  FOR UPDATE;

  IF v_existing_slug IS NULL THEN
    v_slug := public.allocate_agent_profile_slug(p_slug, v_name);
  ELSIF NULLIF(btrim(p_slug), '') IS NULL THEN
    v_slug := v_existing_slug;
  ELSIF public.slugify_agent_profile_name(p_slug) = v_existing_slug THEN
    v_slug := v_existing_slug;
  ELSE
    v_slug := public.allocate_agent_profile_slug(p_slug, v_name);
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.agent_profiles
    WHERE slug = v_slug AND user_id <> v_actor
  ) OR EXISTS (
    SELECT 1
    FROM public.agent_profile_slug_aliases alias_row
    JOIN public.agent_profiles ap ON ap.id = alias_row.agent_profile_id
    WHERE alias_row.old_slug = v_slug AND ap.user_id <> v_actor
  ) THEN
    RAISE EXCEPTION 'Slug đã được sử dụng' USING ERRCODE = '23505';
  END IF;

  UPDATE public.profiles
  SET display_name = NULLIF(btrim(p_display_name), ''),
      phone = v_phone,
      updated_at = now()
  WHERE id = v_actor;

  INSERT INTO public.agent_profiles (
    user_id, slug, display_name, bio, avatar_url, public_phone, public_zalo, status, updated_at
  ) VALUES (
    v_actor, v_slug, v_name, NULLIF(btrim(p_bio), ''),
    (SELECT NULLIF(btrim(avatar_url), '') FROM public.profiles WHERE id = v_actor),
    v_phone, NULLIF(btrim(p_public_zalo), ''), 'published', now()
  )
  ON CONFLICT (user_id) DO UPDATE SET
    slug = EXCLUDED.slug,
    display_name = EXCLUDED.display_name,
    bio = EXCLUDED.bio,
    avatar_url = EXCLUDED.avatar_url,
    public_phone = EXCLUDED.public_phone,
    public_zalo = EXCLUDED.public_zalo,
    status = CASE WHEN agent_profiles.status = 'disabled' THEN 'disabled' ELSE 'published' END,
    updated_at = now()
  RETURNING * INTO v_profile;

  RETURN v_profile;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_agent_profile(
  p_profile_id uuid,
  p_patch jsonb
)
RETURNS public.agent_profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_current public.agent_profiles;
  v_result public.agent_profiles;
  v_is_admin boolean := public.is_admin();
  v_slug text;
  v_requested_slug text;
  v_name text;
BEGIN
  IF auth.uid() IS NULL OR NOT public.is_admin_or_staff() THEN
    RAISE EXCEPTION 'Không có quyền sửa hồ sơ' USING ERRCODE = '42501';
  END IF;
  IF p_patch IS NULL OR jsonb_typeof(p_patch) <> 'object' THEN
    RAISE EXCEPTION 'Dữ liệu hồ sơ không hợp lệ' USING ERRCODE = '22023';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_object_keys(p_patch) AS item(key)
    WHERE key NOT IN ('slug', 'display_name', 'bio', 'avatar_url', 'public_phone', 'public_zalo', 'status')
  ) THEN
    RAISE EXCEPTION 'Trường hồ sơ không được phép' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_current
  FROM public.agent_profiles
  WHERE id = p_profile_id
    AND (v_is_admin OR user_id = auth.uid())
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Không tìm thấy hồ sơ hoặc ngoài phạm vi phụ trách' USING ERRCODE = '42501';
  END IF;
  IF NOT v_is_admin AND p_patch ? 'status' THEN
    RAISE EXCEPTION 'Chỉ admin được thay đổi trạng thái xuất bản' USING ERRCODE = '42501';
  END IF;
  IF p_patch ? 'status' AND (p_patch->>'status') IS NULL THEN
    RAISE EXCEPTION 'Trạng thái hồ sơ không hợp lệ' USING ERRCODE = '22023';
  END IF;
  IF p_patch ? 'status' AND p_patch->>'status' NOT IN ('draft', 'published', 'disabled') THEN
    RAISE EXCEPTION 'Trạng thái hồ sơ không hợp lệ' USING ERRCODE = '22023';
  END IF;
  IF p_patch ? 'slug' AND NULLIF(btrim(p_patch->>'slug'), '') IS NULL THEN
    RAISE EXCEPTION 'Slug hồ sơ không được để trống' USING ERRCODE = '22023';
  END IF;

  v_name := CASE
    WHEN p_patch ? 'display_name' THEN btrim(p_patch->>'display_name')
    ELSE v_current.display_name
  END;
  IF v_name IS NULL OR length(v_name) < 1 OR length(v_name) > 120 THEN
    RAISE EXCEPTION 'Display name must be between 1 and 120 characters' USING ERRCODE = '22023';
  END IF;

  IF p_patch ? 'slug' THEN
    v_requested_slug := public.slugify_agent_profile_name(p_patch->>'slug');
    v_slug := CASE
      WHEN v_requested_slug = v_current.slug THEN v_current.slug
      ELSE public.allocate_agent_profile_slug(v_requested_slug, v_name)
    END;
  ELSE
    v_slug := v_current.slug;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.agent_profiles
    WHERE slug = v_slug AND id <> p_profile_id
  ) OR EXISTS (
    SELECT 1
    FROM public.agent_profile_slug_aliases alias_row
    WHERE alias_row.old_slug = v_slug AND alias_row.agent_profile_id <> p_profile_id
  ) THEN
    RAISE EXCEPTION 'Slug đã được sử dụng' USING ERRCODE = '23505';
  END IF;

  UPDATE public.agent_profiles
  SET slug = v_slug,
      display_name = v_name,
      bio = CASE WHEN p_patch ? 'bio' THEN NULLIF(btrim(p_patch->>'bio'), '') ELSE v_current.bio END,
      avatar_url = CASE WHEN p_patch ? 'avatar_url' THEN NULLIF(btrim(p_patch->>'avatar_url'), '') ELSE v_current.avatar_url END,
      public_phone = CASE WHEN p_patch ? 'public_phone' THEN NULLIF(btrim(p_patch->>'public_phone'), '') ELSE v_current.public_phone END,
      public_zalo = CASE WHEN p_patch ? 'public_zalo' THEN NULLIF(btrim(p_patch->>'public_zalo'), '') ELSE v_current.public_zalo END,
      status = CASE WHEN p_patch ? 'status' THEN p_patch->>'status' ELSE v_current.status END,
      updated_at = now()
  WHERE id = p_profile_id
  RETURNING * INTO v_result;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.provision_agent_profile_from_profile() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.save_my_agent_profile(text, text, text, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.save_my_agent_profile(text, text, text, text, text, text, text) TO authenticated;
REVOKE ALL ON FUNCTION public.save_my_profile_and_agent_profile(text, text, text, text, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.save_my_profile_and_agent_profile(text, text, text, text, text, text, text, text) TO authenticated;
REVOKE ALL ON FUNCTION public.update_agent_profile(uuid, jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_agent_profile(uuid, jsonb) TO authenticated;

NOTIFY pgrst, 'reload schema';
