-- =============================================================================
-- Đợt 5: SEED khu vực 3 cấp cho Bình Dương, TP.HCM, Đồng Nai (nguồn: file Excel)
-- =============================================================================
-- Rebuild districts + wards của 3 tỉnh này theo file chính chủ. Bình Phước GIỮ NGUYÊN.
-- Quy tắc tên (user chốt): bỏ 'Thành phố/Huyện/Phường/Xã/Thị trấn'; GIỮ 'Quận X' và 'Phường <số>'.
-- district/ward lưu TEXT trên listing; district_id/ward_id FK không dùng → null hoá phòng vướng FK.
-- Idempotent qua slug (unique). Chạy trên Supabase Dashboard → SQL Editor.

DO $$
DECLARE v_areas uuid[];
BEGIN
  SELECT array_agg(id) INTO v_areas FROM areas WHERE slug IN ('binh-duong','tp-hcm','dong-nai');
  -- Gỡ tham chiếu district_id (không dùng) để xóa districts cũ không vướng FK
  UPDATE properties    SET district_id = NULL WHERE district_id IN (SELECT id FROM districts WHERE area_id = ANY(v_areas));
  UPDATE user_listings SET district_id = NULL WHERE district_id IN (SELECT id FROM districts WHERE area_id = ANY(v_areas));
  DELETE FROM wards     WHERE district_id IN (SELECT id FROM districts WHERE area_id = ANY(v_areas));
  DELETE FROM districts WHERE area_id = ANY(v_areas);
END $$;

-- Districts
INSERT INTO districts (area_id, name, slug, order_index)
SELECT a.id, v.name, v.slug, v.ord FROM areas a JOIN (VALUES
  ('binh-duong','Thủ Dầu Một','binh-duong-thu-dau-mot',1),
  ('binh-duong','Dĩ An','binh-duong-di-an',2),
  ('binh-duong','Thuận An','binh-duong-thuan-an',3),
  ('binh-duong','Tân Uyên','binh-duong-tan-uyen',4),
  ('binh-duong','Bến Cát','binh-duong-ben-cat',5),
  ('binh-duong','Bàu Bàng','binh-duong-bau-bang',6),
  ('binh-duong','Bắc Tân Uyên','binh-duong-bac-tan-uyen',7),
  ('binh-duong','Phú Giáo','binh-duong-phu-giao',8),
  ('binh-duong','Dầu Tiếng','binh-duong-dau-tieng',9),
  ('tp-hcm','Thủ Đức','tp-hcm-thu-duc',1),
  ('tp-hcm','Quận 1','tp-hcm-quan-1',2),
  ('tp-hcm','Quận 3','tp-hcm-quan-3',3),
  ('tp-hcm','Quận 4','tp-hcm-quan-4',4),
  ('tp-hcm','Quận 5','tp-hcm-quan-5',5),
  ('tp-hcm','Quận 6','tp-hcm-quan-6',6),
  ('tp-hcm','Quận 7','tp-hcm-quan-7',7),
  ('tp-hcm','Quận 8','tp-hcm-quan-8',8),
  ('tp-hcm','Quận 10','tp-hcm-quan-10',9),
  ('tp-hcm','Quận 11','tp-hcm-quan-11',10),
  ('tp-hcm','Quận 12','tp-hcm-quan-12',11),
  ('tp-hcm','Quận Bình Tân','tp-hcm-quan-binh-tan',12),
  ('tp-hcm','Quận Bình Thạnh','tp-hcm-quan-binh-thanh',13),
  ('tp-hcm','Quận Gò Vấp','tp-hcm-quan-go-vap',14),
  ('tp-hcm','Quận Phú Nhuận','tp-hcm-quan-phu-nhuan',15),
  ('tp-hcm','Quận Tân Bình','tp-hcm-quan-tan-binh',16),
  ('tp-hcm','Quận Tân Phú','tp-hcm-quan-tan-phu',17),
  ('tp-hcm','Bình Chánh','tp-hcm-binh-chanh',18),
  ('tp-hcm','Cần Giờ','tp-hcm-can-gio',19),
  ('tp-hcm','Củ Chi','tp-hcm-cu-chi',20),
  ('tp-hcm','Hóc Môn','tp-hcm-hoc-mon',21),
  ('tp-hcm','Nhà Bè','tp-hcm-nha-be',22),
  ('dong-nai','Biên Hòa','dong-nai-bien-hoa',1),
  ('dong-nai','Long Khánh','dong-nai-long-khanh',2),
  ('dong-nai','Cẩm Mỹ','dong-nai-cam-my',3),
  ('dong-nai','Định Quán','dong-nai-dinh-quan',4),
  ('dong-nai','Long Thành','dong-nai-long-thanh',5),
  ('dong-nai','Nhơn Trạch','dong-nai-nhon-trach',6),
  ('dong-nai','Tân Phú','dong-nai-tan-phu',7),
  ('dong-nai','Thống Nhất','dong-nai-thong-nhat',8),
  ('dong-nai','Trảng Bom','dong-nai-trang-bom',9),
  ('dong-nai','Vĩnh Cửu','dong-nai-vinh-cuu',10),
  ('dong-nai','Xuân Lộc','dong-nai-xuan-loc',11)
) AS v(area_slug, name, slug, ord) ON a.slug = v.area_slug;

-- Wards
INSERT INTO wards (district_id, name, slug, order_index)
SELECT d.id, v.name, v.slug, v.ord FROM districts d JOIN (VALUES
  ('binh-duong-thu-dau-mot','Chánh Mỹ','binh-duong-thu-dau-mot-chanh-my',1),
  ('binh-duong-thu-dau-mot','Chánh Nghĩa','binh-duong-thu-dau-mot-chanh-nghia',2),
  ('binh-duong-thu-dau-mot','Định Hòa','binh-duong-thu-dau-mot-dinh-hoa',3),
  ('binh-duong-thu-dau-mot','Hiệp An','binh-duong-thu-dau-mot-hiep-an',4),
  ('binh-duong-thu-dau-mot','Hiệp Thành','binh-duong-thu-dau-mot-hiep-thanh',5),
  ('binh-duong-thu-dau-mot','Hòa Phú','binh-duong-thu-dau-mot-hoa-phu',6),
  ('binh-duong-thu-dau-mot','Phú Cường','binh-duong-thu-dau-mot-phu-cuong',7),
  ('binh-duong-thu-dau-mot','Phú Hòa','binh-duong-thu-dau-mot-phu-hoa',8),
  ('binh-duong-thu-dau-mot','Phú Lợi','binh-duong-thu-dau-mot-phu-loi',9),
  ('binh-duong-thu-dau-mot','Phú Mỹ','binh-duong-thu-dau-mot-phu-my',10),
  ('binh-duong-thu-dau-mot','Phú Tân','binh-duong-thu-dau-mot-phu-tan',11),
  ('binh-duong-thu-dau-mot','Phú Thọ','binh-duong-thu-dau-mot-phu-tho',12),
  ('binh-duong-thu-dau-mot','Tân An','binh-duong-thu-dau-mot-tan-an',13),
  ('binh-duong-thu-dau-mot','Tương Bình Hiệp','binh-duong-thu-dau-mot-tuong-binh-hiep',14),
  ('binh-duong-di-an','An Bình','binh-duong-di-an-an-binh',1),
  ('binh-duong-di-an','Bình An','binh-duong-di-an-binh-an',2),
  ('binh-duong-di-an','Bình Thắng','binh-duong-di-an-binh-thang',3),
  ('binh-duong-di-an','Dĩ An','binh-duong-di-an-di-an',4),
  ('binh-duong-di-an','Đông Hòa','binh-duong-di-an-dong-hoa',5),
  ('binh-duong-di-an','Tân Bình','binh-duong-di-an-tan-binh',6),
  ('binh-duong-di-an','Tân Đông Hiệp','binh-duong-di-an-tan-dong-hiep',7),
  ('binh-duong-thuan-an','An Phú','binh-duong-thuan-an-an-phu',1),
  ('binh-duong-thuan-an','An Thạnh','binh-duong-thuan-an-an-thanh',2),
  ('binh-duong-thuan-an','Bình Chuẩn','binh-duong-thuan-an-binh-chuan',3),
  ('binh-duong-thuan-an','Bình Hòa','binh-duong-thuan-an-binh-hoa',4),
  ('binh-duong-thuan-an','Bình Nhâm','binh-duong-thuan-an-binh-nham',5),
  ('binh-duong-thuan-an','Hưng Định','binh-duong-thuan-an-hung-dinh',6),
  ('binh-duong-thuan-an','Lái Thiêu','binh-duong-thuan-an-lai-thieu',7),
  ('binh-duong-thuan-an','Thuận Giao','binh-duong-thuan-an-thuan-giao',8),
  ('binh-duong-thuan-an','Vĩnh Phú','binh-duong-thuan-an-vinh-phu',9),
  ('binh-duong-thuan-an','An Sơn','binh-duong-thuan-an-an-son',10),
  ('binh-duong-tan-uyen','Hội Nghĩa','binh-duong-tan-uyen-hoi-nghia',1),
  ('binh-duong-tan-uyen','Khánh Bình','binh-duong-tan-uyen-khanh-binh',2),
  ('binh-duong-tan-uyen','Phú Chánh','binh-duong-tan-uyen-phu-chanh',3),
  ('binh-duong-tan-uyen','Tân Hiệp','binh-duong-tan-uyen-tan-hiep',4),
  ('binh-duong-tan-uyen','Tân Phước Khánh','binh-duong-tan-uyen-tan-phuoc-khanh',5),
  ('binh-duong-tan-uyen','Tân Vĩnh Hiệp','binh-duong-tan-uyen-tan-vinh-hiep',6),
  ('binh-duong-tan-uyen','Thái Hòa','binh-duong-tan-uyen-thai-hoa',7),
  ('binh-duong-tan-uyen','Thạnh Phước','binh-duong-tan-uyen-thanh-phuoc',8),
  ('binh-duong-tan-uyen','Uyên Hưng','binh-duong-tan-uyen-uyen-hung',9),
  ('binh-duong-tan-uyen','Vĩnh Tân','binh-duong-tan-uyen-vinh-tan',10),
  ('binh-duong-tan-uyen','Bạch Đằng','binh-duong-tan-uyen-bach-dang',11),
  ('binh-duong-tan-uyen','Thạnh Hội','binh-duong-tan-uyen-thanh-hoi',12),
  ('binh-duong-ben-cat','An Điền','binh-duong-ben-cat-an-dien',1),
  ('binh-duong-ben-cat','An Tây','binh-duong-ben-cat-an-tay',2),
  ('binh-duong-ben-cat','Chánh Phú Hòa','binh-duong-ben-cat-chanh-phu-hoa',3),
  ('binh-duong-ben-cat','Hòa Lợi','binh-duong-ben-cat-hoa-loi',4),
  ('binh-duong-ben-cat','Mỹ Phước','binh-duong-ben-cat-my-phuoc',5),
  ('binh-duong-ben-cat','Tân Định','binh-duong-ben-cat-tan-dinh',6),
  ('binh-duong-ben-cat','Thới Hòa','binh-duong-ben-cat-thoi-hoa',7),
  ('binh-duong-ben-cat','Phú An','binh-duong-ben-cat-phu-an',8),
  ('binh-duong-bau-bang','Lai Uyên','binh-duong-bau-bang-lai-uyen',1),
  ('binh-duong-bau-bang','Cây Trường II','binh-duong-bau-bang-cay-truong-ii',2),
  ('binh-duong-bau-bang','Hưng Hòa','binh-duong-bau-bang-hung-hoa',3),
  ('binh-duong-bau-bang','Lai Hưng','binh-duong-bau-bang-lai-hung',4),
  ('binh-duong-bau-bang','Long Nguyên','binh-duong-bau-bang-long-nguyen',5),
  ('binh-duong-bau-bang','Tân Hưng','binh-duong-bau-bang-tan-hung',6),
  ('binh-duong-bau-bang','Trừ Văn Thố','binh-duong-bau-bang-tru-van-tho',7),
  ('binh-duong-bac-tan-uyen','Tân Bình','binh-duong-bac-tan-uyen-tan-binh',1),
  ('binh-duong-bac-tan-uyen','Tân Thành','binh-duong-bac-tan-uyen-tan-thanh',2),
  ('binh-duong-bac-tan-uyen','Bình Mỹ','binh-duong-bac-tan-uyen-binh-my',3),
  ('binh-duong-bac-tan-uyen','Đất Cuốc','binh-duong-bac-tan-uyen-dat-cuoc',4),
  ('binh-duong-bac-tan-uyen','Hiếu Liêm','binh-duong-bac-tan-uyen-hieu-liem',5),
  ('binh-duong-bac-tan-uyen','Lạc An','binh-duong-bac-tan-uyen-lac-an',6),
  ('binh-duong-bac-tan-uyen','Tân Định','binh-duong-bac-tan-uyen-tan-dinh',7),
  ('binh-duong-bac-tan-uyen','Tân Lập','binh-duong-bac-tan-uyen-tan-lap',8),
  ('binh-duong-bac-tan-uyen','Tân Mỹ','binh-duong-bac-tan-uyen-tan-my',9),
  ('binh-duong-bac-tan-uyen','Thường Tân','binh-duong-bac-tan-uyen-thuong-tan',10),
  ('binh-duong-phu-giao','Phước Vĩnh','binh-duong-phu-giao-phuoc-vinh',1),
  ('binh-duong-phu-giao','An Bình','binh-duong-phu-giao-an-binh',2),
  ('binh-duong-phu-giao','An Linh','binh-duong-phu-giao-an-linh',3),
  ('binh-duong-phu-giao','An Long','binh-duong-phu-giao-an-long',4),
  ('binh-duong-phu-giao','An Thái','binh-duong-phu-giao-an-thai',5),
  ('binh-duong-phu-giao','Phước Hòa','binh-duong-phu-giao-phuoc-hoa',6),
  ('binh-duong-phu-giao','Phước Sang','binh-duong-phu-giao-phuoc-sang',7),
  ('binh-duong-phu-giao','Tam Lập','binh-duong-phu-giao-tam-lap',8),
  ('binh-duong-phu-giao','Tân Hiệp','binh-duong-phu-giao-tan-hiep',9),
  ('binh-duong-phu-giao','Tân Long','binh-duong-phu-giao-tan-long',10),
  ('binh-duong-phu-giao','Vĩnh Hòa','binh-duong-phu-giao-vinh-hoa',11),
  ('binh-duong-dau-tieng','Dầu Tiếng','binh-duong-dau-tieng-dau-tieng',1),
  ('binh-duong-dau-tieng','An Lập','binh-duong-dau-tieng-an-lap',2),
  ('binh-duong-dau-tieng','Định An','binh-duong-dau-tieng-dinh-an',3),
  ('binh-duong-dau-tieng','Định Hiệp','binh-duong-dau-tieng-dinh-hiep',4),
  ('binh-duong-dau-tieng','Định Thành','binh-duong-dau-tieng-dinh-thanh',5),
  ('binh-duong-dau-tieng','Long Hòa','binh-duong-dau-tieng-long-hoa',6),
  ('binh-duong-dau-tieng','Long Tân','binh-duong-dau-tieng-long-tan',7),
  ('binh-duong-dau-tieng','Minh Hòa','binh-duong-dau-tieng-minh-hoa',8),
  ('binh-duong-dau-tieng','Minh Tân','binh-duong-dau-tieng-minh-tan',9),
  ('binh-duong-dau-tieng','Minh Thạnh','binh-duong-dau-tieng-minh-thanh',10),
  ('binh-duong-dau-tieng','Thanh An','binh-duong-dau-tieng-thanh-an',11),
  ('binh-duong-dau-tieng','Thanh Tuyền','binh-duong-dau-tieng-thanh-tuyen',12),
  ('tp-hcm-thu-duc','An Khánh','tp-hcm-thu-duc-an-khanh',1),
  ('tp-hcm-thu-duc','An Lợi Đông','tp-hcm-thu-duc-an-loi-dong',2),
  ('tp-hcm-thu-duc','An Phú','tp-hcm-thu-duc-an-phu',3),
  ('tp-hcm-thu-duc','Bình Chiểu','tp-hcm-thu-duc-binh-chieu',4),
  ('tp-hcm-thu-duc','Bình Thọ','tp-hcm-thu-duc-binh-tho',5),
  ('tp-hcm-thu-duc','Bình Trưng Đông','tp-hcm-thu-duc-binh-trung-dong',6),
  ('tp-hcm-thu-duc','Bình Trưng Tây','tp-hcm-thu-duc-binh-trung-tay',7),
  ('tp-hcm-thu-duc','Cát Lái','tp-hcm-thu-duc-cat-lai',8),
  ('tp-hcm-thu-duc','Hiệp Bình Chánh','tp-hcm-thu-duc-hiep-binh-chanh',9),
  ('tp-hcm-thu-duc','Hiệp Bình Phước','tp-hcm-thu-duc-hiep-binh-phuoc',10),
  ('tp-hcm-thu-duc','Hiệp Phú','tp-hcm-thu-duc-hiep-phu',11),
  ('tp-hcm-thu-duc','Linh Chiểu','tp-hcm-thu-duc-linh-chieu',12),
  ('tp-hcm-thu-duc','Linh Đông','tp-hcm-thu-duc-linh-dong',13),
  ('tp-hcm-thu-duc','Linh Tây','tp-hcm-thu-duc-linh-tay',14),
  ('tp-hcm-thu-duc','Linh Trung','tp-hcm-thu-duc-linh-trung',15),
  ('tp-hcm-thu-duc','Linh Xuân','tp-hcm-thu-duc-linh-xuan',16),
  ('tp-hcm-thu-duc','Long Bình','tp-hcm-thu-duc-long-binh',17),
  ('tp-hcm-thu-duc','Long Phước','tp-hcm-thu-duc-long-phuoc',18),
  ('tp-hcm-thu-duc','Long Thạnh Mỹ','tp-hcm-thu-duc-long-thanh-my',19),
  ('tp-hcm-thu-duc','Long Trường','tp-hcm-thu-duc-long-truong',20),
  ('tp-hcm-thu-duc','Phú Hữu','tp-hcm-thu-duc-phu-huu',21),
  ('tp-hcm-thu-duc','Phước Bình','tp-hcm-thu-duc-phuoc-binh',22),
  ('tp-hcm-thu-duc','Phước Long A','tp-hcm-thu-duc-phuoc-long-a',23),
  ('tp-hcm-thu-duc','Phước Long B','tp-hcm-thu-duc-phuoc-long-b',24),
  ('tp-hcm-thu-duc','Tam Bình','tp-hcm-thu-duc-tam-binh',25),
  ('tp-hcm-thu-duc','Tam Phú','tp-hcm-thu-duc-tam-phu',26),
  ('tp-hcm-thu-duc','Tân Phú','tp-hcm-thu-duc-tan-phu',27),
  ('tp-hcm-thu-duc','Tăng Nhơn Phú A','tp-hcm-thu-duc-tang-nhon-phu-a',28),
  ('tp-hcm-thu-duc','Tăng Nhơn Phú B','tp-hcm-thu-duc-tang-nhon-phu-b',29),
  ('tp-hcm-thu-duc','Thạnh Mỹ Lợi','tp-hcm-thu-duc-thanh-my-loi',30),
  ('tp-hcm-thu-duc','Thảo Điền','tp-hcm-thu-duc-thao-dien',31),
  ('tp-hcm-thu-duc','Thủ Thiêm','tp-hcm-thu-duc-thu-thiem',32),
  ('tp-hcm-thu-duc','Trường Thọ','tp-hcm-thu-duc-truong-tho',33),
  ('tp-hcm-quan-1','Bến Nghé','tp-hcm-quan-1-ben-nghe',1),
  ('tp-hcm-quan-1','Bến Thành','tp-hcm-quan-1-ben-thanh',2),
  ('tp-hcm-quan-1','Cô Giang','tp-hcm-quan-1-co-giang',3),
  ('tp-hcm-quan-1','Cầu Kho','tp-hcm-quan-1-cau-kho',4),
  ('tp-hcm-quan-1','Cầu Ông Lãnh','tp-hcm-quan-1-cau-ong-lanh',5),
  ('tp-hcm-quan-1','Đa Kao','tp-hcm-quan-1-da-kao',6),
  ('tp-hcm-quan-1','Nguyễn Cư Trinh','tp-hcm-quan-1-nguyen-cu-trinh',7),
  ('tp-hcm-quan-1','Nguyễn Thái Bình','tp-hcm-quan-1-nguyen-thai-binh',8),
  ('tp-hcm-quan-1','Phạm Ngũ Lão','tp-hcm-quan-1-pham-ngu-lao',9),
  ('tp-hcm-quan-1','Tân Định','tp-hcm-quan-1-tan-dinh',10),
  ('tp-hcm-quan-3','Phường 1','tp-hcm-quan-3-phuong-1',1),
  ('tp-hcm-quan-3','Phường 2','tp-hcm-quan-3-phuong-2',2),
  ('tp-hcm-quan-3','Phường 3','tp-hcm-quan-3-phuong-3',3),
  ('tp-hcm-quan-3','Phường 4','tp-hcm-quan-3-phuong-4',4),
  ('tp-hcm-quan-3','Phường 5','tp-hcm-quan-3-phuong-5',5),
  ('tp-hcm-quan-3','Phường 9','tp-hcm-quan-3-phuong-9',6),
  ('tp-hcm-quan-3','Phường 10','tp-hcm-quan-3-phuong-10',7),
  ('tp-hcm-quan-3','Phường 11','tp-hcm-quan-3-phuong-11',8),
  ('tp-hcm-quan-3','Phường 12','tp-hcm-quan-3-phuong-12',9),
  ('tp-hcm-quan-3','Phường 13','tp-hcm-quan-3-phuong-13',10),
  ('tp-hcm-quan-3','Phường 14','tp-hcm-quan-3-phuong-14',11),
  ('tp-hcm-quan-3','Võ Thị Sáu','tp-hcm-quan-3-vo-thi-sau',12),
  ('tp-hcm-quan-4','Phường 1','tp-hcm-quan-4-phuong-1',1),
  ('tp-hcm-quan-4','Phường 2','tp-hcm-quan-4-phuong-2',2),
  ('tp-hcm-quan-4','Phường 3','tp-hcm-quan-4-phuong-3',3),
  ('tp-hcm-quan-4','Phường 4','tp-hcm-quan-4-phuong-4',4),
  ('tp-hcm-quan-4','Phường 6','tp-hcm-quan-4-phuong-6',5),
  ('tp-hcm-quan-4','Phường 8','tp-hcm-quan-4-phuong-8',6),
  ('tp-hcm-quan-4','Phường 9','tp-hcm-quan-4-phuong-9',7),
  ('tp-hcm-quan-4','Phường 10','tp-hcm-quan-4-phuong-10',8),
  ('tp-hcm-quan-4','Phường 13','tp-hcm-quan-4-phuong-13',9),
  ('tp-hcm-quan-4','Phường 14','tp-hcm-quan-4-phuong-14',10),
  ('tp-hcm-quan-4','Phường 15','tp-hcm-quan-4-phuong-15',11),
  ('tp-hcm-quan-4','Phường 16','tp-hcm-quan-4-phuong-16',12),
  ('tp-hcm-quan-4','Phường 18','tp-hcm-quan-4-phuong-18',13),
  ('tp-hcm-quan-5','Phường 1','tp-hcm-quan-5-phuong-1',1),
  ('tp-hcm-quan-5','Phường 2','tp-hcm-quan-5-phuong-2',2),
  ('tp-hcm-quan-5','Phường 3','tp-hcm-quan-5-phuong-3',3),
  ('tp-hcm-quan-5','Phường 4','tp-hcm-quan-5-phuong-4',4),
  ('tp-hcm-quan-5','Phường 5','tp-hcm-quan-5-phuong-5',5),
  ('tp-hcm-quan-5','Phường 6','tp-hcm-quan-5-phuong-6',6),
  ('tp-hcm-quan-5','Phường 7','tp-hcm-quan-5-phuong-7',7),
  ('tp-hcm-quan-5','Phường 8','tp-hcm-quan-5-phuong-8',8),
  ('tp-hcm-quan-5','Phường 9','tp-hcm-quan-5-phuong-9',9),
  ('tp-hcm-quan-5','Phường 10','tp-hcm-quan-5-phuong-10',10),
  ('tp-hcm-quan-5','Phường 11','tp-hcm-quan-5-phuong-11',11),
  ('tp-hcm-quan-5','Phường 12','tp-hcm-quan-5-phuong-12',12),
  ('tp-hcm-quan-5','Phường 13','tp-hcm-quan-5-phuong-13',13),
  ('tp-hcm-quan-5','Phường 14','tp-hcm-quan-5-phuong-14',14),
  ('tp-hcm-quan-6','Phường 1','tp-hcm-quan-6-phuong-1',1),
  ('tp-hcm-quan-6','Phường 2','tp-hcm-quan-6-phuong-2',2),
  ('tp-hcm-quan-6','Phường 3','tp-hcm-quan-6-phuong-3',3),
  ('tp-hcm-quan-6','Phường 4','tp-hcm-quan-6-phuong-4',4),
  ('tp-hcm-quan-6','Phường 5','tp-hcm-quan-6-phuong-5',5),
  ('tp-hcm-quan-6','Phường 6','tp-hcm-quan-6-phuong-6',6),
  ('tp-hcm-quan-6','Phường 7','tp-hcm-quan-6-phuong-7',7),
  ('tp-hcm-quan-6','Phường 8','tp-hcm-quan-6-phuong-8',8),
  ('tp-hcm-quan-6','Phường 9','tp-hcm-quan-6-phuong-9',9),
  ('tp-hcm-quan-6','Phường 10','tp-hcm-quan-6-phuong-10',10),
  ('tp-hcm-quan-6','Phường 11','tp-hcm-quan-6-phuong-11',11),
  ('tp-hcm-quan-6','Phường 12','tp-hcm-quan-6-phuong-12',12),
  ('tp-hcm-quan-6','Phường 13','tp-hcm-quan-6-phuong-13',13),
  ('tp-hcm-quan-6','Phường 14','tp-hcm-quan-6-phuong-14',14),
  ('tp-hcm-quan-7','Bình Thuận','tp-hcm-quan-7-binh-thuan',1),
  ('tp-hcm-quan-7','Phú Mỹ','tp-hcm-quan-7-phu-my',2),
  ('tp-hcm-quan-7','Phú Thuận','tp-hcm-quan-7-phu-thuan',3),
  ('tp-hcm-quan-7','Tân Hưng','tp-hcm-quan-7-tan-hung',4),
  ('tp-hcm-quan-7','Tân Kiểng','tp-hcm-quan-7-tan-kieng',5),
  ('tp-hcm-quan-7','Tân Phong','tp-hcm-quan-7-tan-phong',6),
  ('tp-hcm-quan-7','Tân Phú','tp-hcm-quan-7-tan-phu',7),
  ('tp-hcm-quan-7','Tân Quy','tp-hcm-quan-7-tan-quy',8),
  ('tp-hcm-quan-7','Tân Thuận Đông','tp-hcm-quan-7-tan-thuan-dong',9),
  ('tp-hcm-quan-7','Tân Thuận Tây','tp-hcm-quan-7-tan-thuan-tay',10),
  ('tp-hcm-quan-8','Phường 1','tp-hcm-quan-8-phuong-1',1),
  ('tp-hcm-quan-8','Phường 2','tp-hcm-quan-8-phuong-2',2),
  ('tp-hcm-quan-8','Phường 3','tp-hcm-quan-8-phuong-3',3),
  ('tp-hcm-quan-8','Phường 4','tp-hcm-quan-8-phuong-4',4),
  ('tp-hcm-quan-8','Phường 5','tp-hcm-quan-8-phuong-5',5),
  ('tp-hcm-quan-8','Phường 6','tp-hcm-quan-8-phuong-6',6),
  ('tp-hcm-quan-8','Phường 7','tp-hcm-quan-8-phuong-7',7),
  ('tp-hcm-quan-8','Phường 8','tp-hcm-quan-8-phuong-8',8),
  ('tp-hcm-quan-8','Phường 9','tp-hcm-quan-8-phuong-9',9),
  ('tp-hcm-quan-8','Phường 10','tp-hcm-quan-8-phuong-10',10),
  ('tp-hcm-quan-8','Phường 11','tp-hcm-quan-8-phuong-11',11),
  ('tp-hcm-quan-8','Phường 12','tp-hcm-quan-8-phuong-12',12),
  ('tp-hcm-quan-8','Phường 13','tp-hcm-quan-8-phuong-13',13),
  ('tp-hcm-quan-8','Phường 14','tp-hcm-quan-8-phuong-14',14),
  ('tp-hcm-quan-8','Phường 15','tp-hcm-quan-8-phuong-15',15),
  ('tp-hcm-quan-8','Phường 16','tp-hcm-quan-8-phuong-16',16),
  ('tp-hcm-quan-10','Phường 1','tp-hcm-quan-10-phuong-1',1),
  ('tp-hcm-quan-10','Phường 2','tp-hcm-quan-10-phuong-2',2),
  ('tp-hcm-quan-10','Phường 4','tp-hcm-quan-10-phuong-4',3),
  ('tp-hcm-quan-10','Phường 5','tp-hcm-quan-10-phuong-5',4),
  ('tp-hcm-quan-10','Phường 6','tp-hcm-quan-10-phuong-6',5),
  ('tp-hcm-quan-10','Phường 7','tp-hcm-quan-10-phuong-7',6),
  ('tp-hcm-quan-10','Phường 8','tp-hcm-quan-10-phuong-8',7),
  ('tp-hcm-quan-10','Phường 9','tp-hcm-quan-10-phuong-9',8),
  ('tp-hcm-quan-10','Phường 10','tp-hcm-quan-10-phuong-10',9),
  ('tp-hcm-quan-10','Phường 11','tp-hcm-quan-10-phuong-11',10),
  ('tp-hcm-quan-10','Phường 12','tp-hcm-quan-10-phuong-12',11),
  ('tp-hcm-quan-10','Phường 13','tp-hcm-quan-10-phuong-13',12),
  ('tp-hcm-quan-10','Phường 14','tp-hcm-quan-10-phuong-14',13),
  ('tp-hcm-quan-10','Phường 15','tp-hcm-quan-10-phuong-15',14),
  ('tp-hcm-quan-11','Phường 1','tp-hcm-quan-11-phuong-1',1),
  ('tp-hcm-quan-11','Phường 2','tp-hcm-quan-11-phuong-2',2),
  ('tp-hcm-quan-11','Phường 3','tp-hcm-quan-11-phuong-3',3),
  ('tp-hcm-quan-11','Phường 4','tp-hcm-quan-11-phuong-4',4),
  ('tp-hcm-quan-11','Phường 5','tp-hcm-quan-11-phuong-5',5),
  ('tp-hcm-quan-11','Phường 6','tp-hcm-quan-11-phuong-6',6),
  ('tp-hcm-quan-11','Phường 7','tp-hcm-quan-11-phuong-7',7),
  ('tp-hcm-quan-11','Phường 8','tp-hcm-quan-11-phuong-8',8),
  ('tp-hcm-quan-11','Phường 9','tp-hcm-quan-11-phuong-9',9),
  ('tp-hcm-quan-11','Phường 10','tp-hcm-quan-11-phuong-10',10),
  ('tp-hcm-quan-11','Phường 11','tp-hcm-quan-11-phuong-11',11),
  ('tp-hcm-quan-11','Phường 12','tp-hcm-quan-11-phuong-12',12),
  ('tp-hcm-quan-11','Phường 13','tp-hcm-quan-11-phuong-13',13),
  ('tp-hcm-quan-11','Phường 14','tp-hcm-quan-11-phuong-14',14),
  ('tp-hcm-quan-11','Phường 15','tp-hcm-quan-11-phuong-15',15),
  ('tp-hcm-quan-11','Phường 16','tp-hcm-quan-11-phuong-16',16),
  ('tp-hcm-quan-12','An Phú Đông','tp-hcm-quan-12-an-phu-dong',1),
  ('tp-hcm-quan-12','Đông Hưng Thuận','tp-hcm-quan-12-dong-hung-thuan',2),
  ('tp-hcm-quan-12','Hiệp Thành','tp-hcm-quan-12-hiep-thanh',3),
  ('tp-hcm-quan-12','Tân Chánh Hiệp','tp-hcm-quan-12-tan-chanh-hiep',4),
  ('tp-hcm-quan-12','Tân Hưng Thuận','tp-hcm-quan-12-tan-hung-thuan',5),
  ('tp-hcm-quan-12','Tân Thới Hiệp','tp-hcm-quan-12-tan-thoi-hiep',6),
  ('tp-hcm-quan-12','Tân Thới Nhất','tp-hcm-quan-12-tan-thoi-nhat',7),
  ('tp-hcm-quan-12','Thạnh Lộc','tp-hcm-quan-12-thanh-loc',8),
  ('tp-hcm-quan-12','Thạnh Xuân','tp-hcm-quan-12-thanh-xuan',9),
  ('tp-hcm-quan-12','Thới An','tp-hcm-quan-12-thoi-an',10),
  ('tp-hcm-quan-12','Trung Mỹ Tây','tp-hcm-quan-12-trung-my-tay',11),
  ('tp-hcm-quan-binh-tan','An Lạc','tp-hcm-quan-binh-tan-an-lac',1),
  ('tp-hcm-quan-binh-tan','An Lạc A','tp-hcm-quan-binh-tan-an-lac-a',2),
  ('tp-hcm-quan-binh-tan','Bình Hưng Hòa','tp-hcm-quan-binh-tan-binh-hung-hoa',3),
  ('tp-hcm-quan-binh-tan','Bình Hưng Hòa A','tp-hcm-quan-binh-tan-binh-hung-hoa-a',4),
  ('tp-hcm-quan-binh-tan','Bình Hưng Hòa B','tp-hcm-quan-binh-tan-binh-hung-hoa-b',5),
  ('tp-hcm-quan-binh-tan','Bình Trị Đông','tp-hcm-quan-binh-tan-binh-tri-dong',6),
  ('tp-hcm-quan-binh-tan','Bình Trị Đông A','tp-hcm-quan-binh-tan-binh-tri-dong-a',7),
  ('tp-hcm-quan-binh-tan','Bình Trị Đông B','tp-hcm-quan-binh-tan-binh-tri-dong-b',8),
  ('tp-hcm-quan-binh-tan','Tân Tạo','tp-hcm-quan-binh-tan-tan-tao',9),
  ('tp-hcm-quan-binh-tan','Tân Tạo A','tp-hcm-quan-binh-tan-tan-tao-a',10),
  ('tp-hcm-quan-binh-thanh','Phường 1','tp-hcm-quan-binh-thanh-phuong-1',1),
  ('tp-hcm-quan-binh-thanh','Phường 2','tp-hcm-quan-binh-thanh-phuong-2',2),
  ('tp-hcm-quan-binh-thanh','Phường 3','tp-hcm-quan-binh-thanh-phuong-3',3),
  ('tp-hcm-quan-binh-thanh','Phường 5','tp-hcm-quan-binh-thanh-phuong-5',4),
  ('tp-hcm-quan-binh-thanh','Phường 6','tp-hcm-quan-binh-thanh-phuong-6',5),
  ('tp-hcm-quan-binh-thanh','Phường 7','tp-hcm-quan-binh-thanh-phuong-7',6),
  ('tp-hcm-quan-binh-thanh','Phường 11','tp-hcm-quan-binh-thanh-phuong-11',7),
  ('tp-hcm-quan-binh-thanh','Phường 12','tp-hcm-quan-binh-thanh-phuong-12',8),
  ('tp-hcm-quan-binh-thanh','Phường 13','tp-hcm-quan-binh-thanh-phuong-13',9),
  ('tp-hcm-quan-binh-thanh','Phường 14','tp-hcm-quan-binh-thanh-phuong-14',10),
  ('tp-hcm-quan-binh-thanh','Phường 15','tp-hcm-quan-binh-thanh-phuong-15',11),
  ('tp-hcm-quan-binh-thanh','Phường 17','tp-hcm-quan-binh-thanh-phuong-17',12),
  ('tp-hcm-quan-binh-thanh','Phường 19','tp-hcm-quan-binh-thanh-phuong-19',13),
  ('tp-hcm-quan-binh-thanh','Phường 21','tp-hcm-quan-binh-thanh-phuong-21',14),
  ('tp-hcm-quan-binh-thanh','Phường 22','tp-hcm-quan-binh-thanh-phuong-22',15),
  ('tp-hcm-quan-binh-thanh','Phường 24','tp-hcm-quan-binh-thanh-phuong-24',16),
  ('tp-hcm-quan-binh-thanh','Phường 25','tp-hcm-quan-binh-thanh-phuong-25',17),
  ('tp-hcm-quan-binh-thanh','Phường 26','tp-hcm-quan-binh-thanh-phuong-26',18),
  ('tp-hcm-quan-binh-thanh','Phường 27','tp-hcm-quan-binh-thanh-phuong-27',19),
  ('tp-hcm-quan-binh-thanh','Phường 28','tp-hcm-quan-binh-thanh-phuong-28',20),
  ('tp-hcm-quan-go-vap','Phường 1','tp-hcm-quan-go-vap-phuong-1',1),
  ('tp-hcm-quan-go-vap','Phường 3','tp-hcm-quan-go-vap-phuong-3',2),
  ('tp-hcm-quan-go-vap','Phường 4','tp-hcm-quan-go-vap-phuong-4',3),
  ('tp-hcm-quan-go-vap','Phường 5','tp-hcm-quan-go-vap-phuong-5',4),
  ('tp-hcm-quan-go-vap','Phường 6','tp-hcm-quan-go-vap-phuong-6',5),
  ('tp-hcm-quan-go-vap','Phường 7','tp-hcm-quan-go-vap-phuong-7',6),
  ('tp-hcm-quan-go-vap','Phường 8','tp-hcm-quan-go-vap-phuong-8',7),
  ('tp-hcm-quan-go-vap','Phường 9','tp-hcm-quan-go-vap-phuong-9',8),
  ('tp-hcm-quan-go-vap','Phường 10','tp-hcm-quan-go-vap-phuong-10',9),
  ('tp-hcm-quan-go-vap','Phường 11','tp-hcm-quan-go-vap-phuong-11',10),
  ('tp-hcm-quan-go-vap','Phường 12','tp-hcm-quan-go-vap-phuong-12',11),
  ('tp-hcm-quan-go-vap','Phường 13','tp-hcm-quan-go-vap-phuong-13',12),
  ('tp-hcm-quan-go-vap','Phường 14','tp-hcm-quan-go-vap-phuong-14',13),
  ('tp-hcm-quan-go-vap','Phường 15','tp-hcm-quan-go-vap-phuong-15',14),
  ('tp-hcm-quan-go-vap','Phường 16','tp-hcm-quan-go-vap-phuong-16',15),
  ('tp-hcm-quan-go-vap','Phường 17','tp-hcm-quan-go-vap-phuong-17',16),
  ('tp-hcm-quan-phu-nhuan','Phường 1','tp-hcm-quan-phu-nhuan-phuong-1',1),
  ('tp-hcm-quan-phu-nhuan','Phường 2','tp-hcm-quan-phu-nhuan-phuong-2',2),
  ('tp-hcm-quan-phu-nhuan','Phường 3','tp-hcm-quan-phu-nhuan-phuong-3',3),
  ('tp-hcm-quan-phu-nhuan','Phường 4','tp-hcm-quan-phu-nhuan-phuong-4',4),
  ('tp-hcm-quan-phu-nhuan','Phường 5','tp-hcm-quan-phu-nhuan-phuong-5',5),
  ('tp-hcm-quan-phu-nhuan','Phường 7','tp-hcm-quan-phu-nhuan-phuong-7',6),
  ('tp-hcm-quan-phu-nhuan','Phường 8','tp-hcm-quan-phu-nhuan-phuong-8',7),
  ('tp-hcm-quan-phu-nhuan','Phường 9','tp-hcm-quan-phu-nhuan-phuong-9',8),
  ('tp-hcm-quan-phu-nhuan','Phường 10','tp-hcm-quan-phu-nhuan-phuong-10',9),
  ('tp-hcm-quan-phu-nhuan','Phường 11','tp-hcm-quan-phu-nhuan-phuong-11',10),
  ('tp-hcm-quan-phu-nhuan','Phường 13','tp-hcm-quan-phu-nhuan-phuong-13',11),
  ('tp-hcm-quan-phu-nhuan','Phường 15','tp-hcm-quan-phu-nhuan-phuong-15',12),
  ('tp-hcm-quan-phu-nhuan','Phường 17','tp-hcm-quan-phu-nhuan-phuong-17',13),
  ('tp-hcm-quan-tan-binh','Phường 1','tp-hcm-quan-tan-binh-phuong-1',1),
  ('tp-hcm-quan-tan-binh','Phường 2','tp-hcm-quan-tan-binh-phuong-2',2),
  ('tp-hcm-quan-tan-binh','Phường 3','tp-hcm-quan-tan-binh-phuong-3',3),
  ('tp-hcm-quan-tan-binh','Phường 4','tp-hcm-quan-tan-binh-phuong-4',4),
  ('tp-hcm-quan-tan-binh','Phường 5','tp-hcm-quan-tan-binh-phuong-5',5),
  ('tp-hcm-quan-tan-binh','Phường 6','tp-hcm-quan-tan-binh-phuong-6',6),
  ('tp-hcm-quan-tan-binh','Phường 7','tp-hcm-quan-tan-binh-phuong-7',7),
  ('tp-hcm-quan-tan-binh','Phường 8','tp-hcm-quan-tan-binh-phuong-8',8),
  ('tp-hcm-quan-tan-binh','Phường 9','tp-hcm-quan-tan-binh-phuong-9',9),
  ('tp-hcm-quan-tan-binh','Phường 10','tp-hcm-quan-tan-binh-phuong-10',10),
  ('tp-hcm-quan-tan-binh','Phường 11','tp-hcm-quan-tan-binh-phuong-11',11),
  ('tp-hcm-quan-tan-binh','Phường 12','tp-hcm-quan-tan-binh-phuong-12',12),
  ('tp-hcm-quan-tan-binh','Phường 13','tp-hcm-quan-tan-binh-phuong-13',13),
  ('tp-hcm-quan-tan-binh','Phường 14','tp-hcm-quan-tan-binh-phuong-14',14),
  ('tp-hcm-quan-tan-binh','Phường 15','tp-hcm-quan-tan-binh-phuong-15',15),
  ('tp-hcm-quan-tan-phu','Hiệp Tân','tp-hcm-quan-tan-phu-hiep-tan',1),
  ('tp-hcm-quan-tan-phu','Hòa Thạnh','tp-hcm-quan-tan-phu-hoa-thanh',2),
  ('tp-hcm-quan-tan-phu','Phú Thạnh','tp-hcm-quan-tan-phu-phu-thanh',3),
  ('tp-hcm-quan-tan-phu','Phú Thọ Hòa','tp-hcm-quan-tan-phu-phu-tho-hoa',4),
  ('tp-hcm-quan-tan-phu','Phú Trung','tp-hcm-quan-tan-phu-phu-trung',5),
  ('tp-hcm-quan-tan-phu','Sơn Kỳ','tp-hcm-quan-tan-phu-son-ky',6),
  ('tp-hcm-quan-tan-phu','Tân Quý','tp-hcm-quan-tan-phu-tan-quy',7),
  ('tp-hcm-quan-tan-phu','Tân Sơn Nhì','tp-hcm-quan-tan-phu-tan-son-nhi',8),
  ('tp-hcm-quan-tan-phu','Tân Thành','tp-hcm-quan-tan-phu-tan-thanh',9),
  ('tp-hcm-quan-tan-phu','Tân Thới Hòa','tp-hcm-quan-tan-phu-tan-thoi-hoa',10),
  ('tp-hcm-quan-tan-phu','Tây Thạnh','tp-hcm-quan-tan-phu-tay-thanh',11),
  ('tp-hcm-binh-chanh','Tân Túc','tp-hcm-binh-chanh-tan-tuc',1),
  ('tp-hcm-binh-chanh','An Phú Tây','tp-hcm-binh-chanh-an-phu-tay',2),
  ('tp-hcm-binh-chanh','Bình Chánh','tp-hcm-binh-chanh-binh-chanh',3),
  ('tp-hcm-binh-chanh','Bình Hưng','tp-hcm-binh-chanh-binh-hung',4),
  ('tp-hcm-binh-chanh','Bình Lợi','tp-hcm-binh-chanh-binh-loi',5),
  ('tp-hcm-binh-chanh','Đa Phước','tp-hcm-binh-chanh-da-phuoc',6),
  ('tp-hcm-binh-chanh','Hưng Long','tp-hcm-binh-chanh-hung-long',7),
  ('tp-hcm-binh-chanh','Lê Minh Xuân','tp-hcm-binh-chanh-le-minh-xuan',8),
  ('tp-hcm-binh-chanh','Phạm Văn Hai','tp-hcm-binh-chanh-pham-van-hai',9),
  ('tp-hcm-binh-chanh','Phong Phú','tp-hcm-binh-chanh-phong-phu',10),
  ('tp-hcm-binh-chanh','Quy Đức','tp-hcm-binh-chanh-quy-duc',11),
  ('tp-hcm-binh-chanh','Tân Kiên','tp-hcm-binh-chanh-tan-kien',12),
  ('tp-hcm-binh-chanh','Tân Nhựt','tp-hcm-binh-chanh-tan-nhut',13),
  ('tp-hcm-binh-chanh','Tân Quý Tây','tp-hcm-binh-chanh-tan-quy-tay',14),
  ('tp-hcm-binh-chanh','Vĩnh Lộc A','tp-hcm-binh-chanh-vinh-loc-a',15),
  ('tp-hcm-binh-chanh','Vĩnh Lộc B','tp-hcm-binh-chanh-vinh-loc-b',16),
  ('tp-hcm-can-gio','Cần Thạnh','tp-hcm-can-gio-can-thanh',1),
  ('tp-hcm-can-gio','An Thới Đông','tp-hcm-can-gio-an-thoi-dong',2),
  ('tp-hcm-can-gio','Bình Khánh','tp-hcm-can-gio-binh-khanh',3),
  ('tp-hcm-can-gio','Long Hòa','tp-hcm-can-gio-long-hoa',4),
  ('tp-hcm-can-gio','Lý Nhơn','tp-hcm-can-gio-ly-nhon',5),
  ('tp-hcm-can-gio','Tam Thôn Hiệp','tp-hcm-can-gio-tam-thon-hiep',6),
  ('tp-hcm-can-gio','Thạnh An','tp-hcm-can-gio-thanh-an',7),
  ('tp-hcm-cu-chi','Củ Chi','tp-hcm-cu-chi-cu-chi',1),
  ('tp-hcm-cu-chi','An Nhơn Tây','tp-hcm-cu-chi-an-nhon-tay',2),
  ('tp-hcm-cu-chi','An Phú','tp-hcm-cu-chi-an-phu',3),
  ('tp-hcm-cu-chi','Bình Mỹ','tp-hcm-cu-chi-binh-my',4),
  ('tp-hcm-cu-chi','Hòa Phú','tp-hcm-cu-chi-hoa-phu',5),
  ('tp-hcm-cu-chi','Nhuận Đức','tp-hcm-cu-chi-nhuan-duc',6),
  ('tp-hcm-cu-chi','Phạm Văn Cội','tp-hcm-cu-chi-pham-van-coi',7),
  ('tp-hcm-cu-chi','Phú Hòa Đông','tp-hcm-cu-chi-phu-hoa-dong',8),
  ('tp-hcm-cu-chi','Phú Mỹ Hưng','tp-hcm-cu-chi-phu-my-hung',9),
  ('tp-hcm-cu-chi','Phước Hiệp','tp-hcm-cu-chi-phuoc-hiep',10),
  ('tp-hcm-cu-chi','Phước Thạnh','tp-hcm-cu-chi-phuoc-thanh',11),
  ('tp-hcm-cu-chi','Phước Vĩnh An','tp-hcm-cu-chi-phuoc-vinh-an',12),
  ('tp-hcm-cu-chi','Tân An Hội','tp-hcm-cu-chi-tan-an-hoi',13),
  ('tp-hcm-cu-chi','Tân Phú Trung','tp-hcm-cu-chi-tan-phu-trung',14),
  ('tp-hcm-cu-chi','Tân Thạnh Đông','tp-hcm-cu-chi-tan-thanh-dong',15),
  ('tp-hcm-cu-chi','Tân Thạnh Tây','tp-hcm-cu-chi-tan-thanh-tay',16),
  ('tp-hcm-cu-chi','Tân Thông Hội','tp-hcm-cu-chi-tan-thong-hoi',17),
  ('tp-hcm-cu-chi','Thái Mỹ','tp-hcm-cu-chi-thai-my',18),
  ('tp-hcm-cu-chi','Trung An','tp-hcm-cu-chi-trung-an',19),
  ('tp-hcm-cu-chi','Trung Lập Hạ','tp-hcm-cu-chi-trung-lap-ha',20),
  ('tp-hcm-cu-chi','Trung Lập Thượng','tp-hcm-cu-chi-trung-lap-thuong',21),
  ('tp-hcm-hoc-mon','Hóc Môn','tp-hcm-hoc-mon-hoc-mon',1),
  ('tp-hcm-hoc-mon','Bà Điểm','tp-hcm-hoc-mon-ba-diem',2),
  ('tp-hcm-hoc-mon','Đông Thạnh','tp-hcm-hoc-mon-dong-thanh',3),
  ('tp-hcm-hoc-mon','Nhị Bình','tp-hcm-hoc-mon-nhi-binh',4),
  ('tp-hcm-hoc-mon','Tân Hiệp','tp-hcm-hoc-mon-tan-hiep',5),
  ('tp-hcm-hoc-mon','Tân Thới Nhì','tp-hcm-hoc-mon-tan-thoi-nhi',6),
  ('tp-hcm-hoc-mon','Tân Xuân','tp-hcm-hoc-mon-tan-xuan',7),
  ('tp-hcm-hoc-mon','Thới Tam Thôn','tp-hcm-hoc-mon-thoi-tam-thon',8),
  ('tp-hcm-hoc-mon','Trung Chánh','tp-hcm-hoc-mon-trung-chanh',9),
  ('tp-hcm-hoc-mon','Xuân Thới Đông','tp-hcm-hoc-mon-xuan-thoi-dong',10),
  ('tp-hcm-hoc-mon','Xuân Thới Sơn','tp-hcm-hoc-mon-xuan-thoi-son',11),
  ('tp-hcm-hoc-mon','Xuân Thới Thượng','tp-hcm-hoc-mon-xuan-thoi-thuong',12),
  ('tp-hcm-nha-be','Nhà Bè','tp-hcm-nha-be-nha-be',1),
  ('tp-hcm-nha-be','Hiệp Phước','tp-hcm-nha-be-hiep-phuoc',2),
  ('tp-hcm-nha-be','Long Thới','tp-hcm-nha-be-long-thoi',3),
  ('tp-hcm-nha-be','Nhơn Đức','tp-hcm-nha-be-nhon-duc',4),
  ('tp-hcm-nha-be','Phú Xuân','tp-hcm-nha-be-phu-xuan',5),
  ('tp-hcm-nha-be','Phước Kiển','tp-hcm-nha-be-phuoc-kien',6),
  ('tp-hcm-nha-be','Phước Lộc','tp-hcm-nha-be-phuoc-loc',7),
  ('dong-nai-bien-hoa','An Bình','dong-nai-bien-hoa-an-binh',1),
  ('dong-nai-bien-hoa','An Hòa','dong-nai-bien-hoa-an-hoa',2),
  ('dong-nai-bien-hoa','Bình Đa','dong-nai-bien-hoa-binh-da',3),
  ('dong-nai-bien-hoa','Bửu Hòa','dong-nai-bien-hoa-buu-hoa',4),
  ('dong-nai-bien-hoa','Bửu Long','dong-nai-bien-hoa-buu-long',5),
  ('dong-nai-bien-hoa','Hiệp Hòa','dong-nai-bien-hoa-hiep-hoa',6),
  ('dong-nai-bien-hoa','Hóa An','dong-nai-bien-hoa-hoa-an',7),
  ('dong-nai-bien-hoa','Hòa Bình','dong-nai-bien-hoa-hoa-binh',8),
  ('dong-nai-bien-hoa','Hố Nai','dong-nai-bien-hoa-ho-nai',9),
  ('dong-nai-bien-hoa','Long Bình','dong-nai-bien-hoa-long-binh',10),
  ('dong-nai-bien-hoa','Long Bình Tân','dong-nai-bien-hoa-long-binh-tan',11),
  ('dong-nai-bien-hoa','Phước Tân','dong-nai-bien-hoa-phuoc-tan',12),
  ('dong-nai-bien-hoa','Quang Vinh','dong-nai-bien-hoa-quang-vinh',13),
  ('dong-nai-bien-hoa','Quyết Thắng','dong-nai-bien-hoa-quyet-thang',14),
  ('dong-nai-bien-hoa','Tam Hiệp','dong-nai-bien-hoa-tam-hiep',15),
  ('dong-nai-bien-hoa','Tam Hòa','dong-nai-bien-hoa-tam-hoa',16),
  ('dong-nai-bien-hoa','Tam Phước','dong-nai-bien-hoa-tam-phuoc',17),
  ('dong-nai-bien-hoa','Tân Biên','dong-nai-bien-hoa-tan-bien',18),
  ('dong-nai-bien-hoa','Tân Hạnh','dong-nai-bien-hoa-tan-hanh',19),
  ('dong-nai-bien-hoa','Tân Hiệp','dong-nai-bien-hoa-tan-hiep',20),
  ('dong-nai-bien-hoa','Tân Hòa','dong-nai-bien-hoa-tan-hoa',21),
  ('dong-nai-bien-hoa','Tân Mai','dong-nai-bien-hoa-tan-mai',22),
  ('dong-nai-bien-hoa','Tân Phong','dong-nai-bien-hoa-tan-phong',23),
  ('dong-nai-bien-hoa','Tân Tiến','dong-nai-bien-hoa-tan-tien',24),
  ('dong-nai-bien-hoa','Tân Vạn','dong-nai-bien-hoa-tan-van',25),
  ('dong-nai-bien-hoa','Thanh Bình','dong-nai-bien-hoa-thanh-binh',26),
  ('dong-nai-bien-hoa','Thống Nhất','dong-nai-bien-hoa-thong-nhat',27),
  ('dong-nai-bien-hoa','Trảng Dài','dong-nai-bien-hoa-trang-dai',28),
  ('dong-nai-bien-hoa','Trung Dũng','dong-nai-bien-hoa-trung-dung',29),
  ('dong-nai-bien-hoa','Long Hưng','dong-nai-bien-hoa-long-hung',30),
  ('dong-nai-long-khanh','Bảo Vinh','dong-nai-long-khanh-bao-vinh',1),
  ('dong-nai-long-khanh','Bàu Sen','dong-nai-long-khanh-bau-sen',2),
  ('dong-nai-long-khanh','Phú Bình','dong-nai-long-khanh-phu-binh',3),
  ('dong-nai-long-khanh','Suối Tre','dong-nai-long-khanh-suoi-tre',4),
  ('dong-nai-long-khanh','Xuân An','dong-nai-long-khanh-xuan-an',5),
  ('dong-nai-long-khanh','Xuân Bình','dong-nai-long-khanh-xuan-binh',6),
  ('dong-nai-long-khanh','Xuân Hòa','dong-nai-long-khanh-xuan-hoa',7),
  ('dong-nai-long-khanh','Xuân Lập','dong-nai-long-khanh-xuan-lap',8),
  ('dong-nai-long-khanh','Xuân Tân','dong-nai-long-khanh-xuan-tan',9),
  ('dong-nai-long-khanh','Xuân Thanh','dong-nai-long-khanh-xuan-thanh',10),
  ('dong-nai-long-khanh','Xuân Trung','dong-nai-long-khanh-xuan-trung',11),
  ('dong-nai-long-khanh','Bảo Quang','dong-nai-long-khanh-bao-quang',12),
  ('dong-nai-long-khanh','Bàu Trâm','dong-nai-long-khanh-bau-tram',13),
  ('dong-nai-long-khanh','Bình Lộc','dong-nai-long-khanh-binh-loc',14),
  ('dong-nai-long-khanh','Hàng Gòn','dong-nai-long-khanh-hang-gon',15),
  ('dong-nai-cam-my','Long Giao','dong-nai-cam-my-long-giao',1),
  ('dong-nai-cam-my','Bảo Bình','dong-nai-cam-my-bao-binh',2),
  ('dong-nai-cam-my','Lâm San','dong-nai-cam-my-lam-san',3),
  ('dong-nai-cam-my','Nhân Nghĩa','dong-nai-cam-my-nhan-nghia',4),
  ('dong-nai-cam-my','Sông Nhạn','dong-nai-cam-my-song-nhan',5),
  ('dong-nai-cam-my','Sông Ray','dong-nai-cam-my-song-ray',6),
  ('dong-nai-cam-my','Thừa Đức','dong-nai-cam-my-thua-duc',7),
  ('dong-nai-cam-my','Xuân Bảo','dong-nai-cam-my-xuan-bao',8),
  ('dong-nai-cam-my','Xuân Đông','dong-nai-cam-my-xuan-dong',9),
  ('dong-nai-cam-my','Xuân Đường','dong-nai-cam-my-xuan-duong',10),
  ('dong-nai-cam-my','Xuân Mỹ','dong-nai-cam-my-xuan-my',11),
  ('dong-nai-cam-my','Xuân Quế','dong-nai-cam-my-xuan-que',12),
  ('dong-nai-cam-my','Xuân Tây','dong-nai-cam-my-xuan-tay',13),
  ('dong-nai-dinh-quan','Định Quán','dong-nai-dinh-quan-dinh-quan',1),
  ('dong-nai-dinh-quan','Gia Canh','dong-nai-dinh-quan-gia-canh',2),
  ('dong-nai-dinh-quan','La Ngà','dong-nai-dinh-quan-la-nga',3),
  ('dong-nai-dinh-quan','Ngọc Định','dong-nai-dinh-quan-ngoc-dinh',4),
  ('dong-nai-dinh-quan','Phú Cường','dong-nai-dinh-quan-phu-cuong',5),
  ('dong-nai-dinh-quan','Phú Hòa','dong-nai-dinh-quan-phu-hoa',6),
  ('dong-nai-dinh-quan','Phú Lợi','dong-nai-dinh-quan-phu-loi',7),
  ('dong-nai-dinh-quan','Phú Ngọc','dong-nai-dinh-quan-phu-ngoc',8),
  ('dong-nai-dinh-quan','Phú Tân','dong-nai-dinh-quan-phu-tan',9),
  ('dong-nai-dinh-quan','Phú Túc','dong-nai-dinh-quan-phu-tuc',10),
  ('dong-nai-dinh-quan','Phú Vinh','dong-nai-dinh-quan-phu-vinh',11),
  ('dong-nai-dinh-quan','Suối Nho','dong-nai-dinh-quan-suoi-nho',12),
  ('dong-nai-dinh-quan','Thanh Sơn','dong-nai-dinh-quan-thanh-son',13),
  ('dong-nai-dinh-quan','Túc Trưng','dong-nai-dinh-quan-tuc-trung',14),
  ('dong-nai-long-thanh','Long Thành','dong-nai-long-thanh-long-thanh',1),
  ('dong-nai-long-thanh','An Phước','dong-nai-long-thanh-an-phuoc',2),
  ('dong-nai-long-thanh','Bàu Cạn','dong-nai-long-thanh-bau-can',3),
  ('dong-nai-long-thanh','Bình An','dong-nai-long-thanh-binh-an',4),
  ('dong-nai-long-thanh','Bình Sơn','dong-nai-long-thanh-binh-son',5),
  ('dong-nai-long-thanh','Cẩm Đường','dong-nai-long-thanh-cam-duong',6),
  ('dong-nai-long-thanh','Lộc An','dong-nai-long-thanh-loc-an',7),
  ('dong-nai-long-thanh','Long An','dong-nai-long-thanh-long-an',8),
  ('dong-nai-long-thanh','Long Đức','dong-nai-long-thanh-long-duc',9),
  ('dong-nai-long-thanh','Long Phước','dong-nai-long-thanh-long-phuoc',10),
  ('dong-nai-long-thanh','Phước Bình','dong-nai-long-thanh-phuoc-binh',11),
  ('dong-nai-long-thanh','Phước Thái','dong-nai-long-thanh-phuoc-thai',12),
  ('dong-nai-long-thanh','Tam An','dong-nai-long-thanh-tam-an',13),
  ('dong-nai-long-thanh','Tân Hiệp','dong-nai-long-thanh-tan-hiep',14),
  ('dong-nai-nhon-trach','Hiệp Phước','dong-nai-nhon-trach-hiep-phuoc',1),
  ('dong-nai-nhon-trach','Đại Phước','dong-nai-nhon-trach-dai-phuoc',2),
  ('dong-nai-nhon-trach','Long Tân','dong-nai-nhon-trach-long-tan',3),
  ('dong-nai-nhon-trach','Long Thọ','dong-nai-nhon-trach-long-tho',4),
  ('dong-nai-nhon-trach','Phú Đông','dong-nai-nhon-trach-phu-dong',5),
  ('dong-nai-nhon-trach','Phú Hội','dong-nai-nhon-trach-phu-hoi',6),
  ('dong-nai-nhon-trach','Phú Hữu','dong-nai-nhon-trach-phu-huu',7),
  ('dong-nai-nhon-trach','Phú Thạnh','dong-nai-nhon-trach-phu-thanh',8),
  ('dong-nai-nhon-trach','Phước An','dong-nai-nhon-trach-phuoc-an',9),
  ('dong-nai-nhon-trach','Phước Khánh','dong-nai-nhon-trach-phuoc-khanh',10),
  ('dong-nai-nhon-trach','Phước Thiền','dong-nai-nhon-trach-phuoc-thien',11),
  ('dong-nai-nhon-trach','Vĩnh Thanh','dong-nai-nhon-trach-vinh-thanh',12),
  ('dong-nai-tan-phu','Tân Phú','dong-nai-tan-phu-tan-phu',1),
  ('dong-nai-tan-phu','Đắc Lua','dong-nai-tan-phu-dac-lua',2),
  ('dong-nai-tan-phu','Nam Cát Tiên','dong-nai-tan-phu-nam-cat-tien',3),
  ('dong-nai-tan-phu','Núi Tượng','dong-nai-tan-phu-nui-tuong',4),
  ('dong-nai-tan-phu','Phú An','dong-nai-tan-phu-phu-an',5),
  ('dong-nai-tan-phu','Phú Bình','dong-nai-tan-phu-phu-binh',6),
  ('dong-nai-tan-phu','Phú Điền','dong-nai-tan-phu-phu-dien',7),
  ('dong-nai-tan-phu','Phú Lâm','dong-nai-tan-phu-phu-lam',8),
  ('dong-nai-tan-phu','Phú Lập','dong-nai-tan-phu-phu-lap',9),
  ('dong-nai-tan-phu','Phú Lộc','dong-nai-tan-phu-phu-loc',10),
  ('dong-nai-tan-phu','Phú Sơn','dong-nai-tan-phu-phu-son',11),
  ('dong-nai-tan-phu','Phú Thanh','dong-nai-tan-phu-phu-thanh',12),
  ('dong-nai-tan-phu','Phú Thịnh','dong-nai-tan-phu-phu-thinh',13),
  ('dong-nai-tan-phu','Phú Trung','dong-nai-tan-phu-phu-trung',14),
  ('dong-nai-tan-phu','Phú Xuân','dong-nai-tan-phu-phu-xuan',15),
  ('dong-nai-tan-phu','Tà Lài','dong-nai-tan-phu-ta-lai',16),
  ('dong-nai-tan-phu','Thanh Sơn','dong-nai-tan-phu-thanh-son',17),
  ('dong-nai-tan-phu','Trà Cổ','dong-nai-tan-phu-tra-co',18),
  ('dong-nai-thong-nhat','Dầu Giây','dong-nai-thong-nhat-dau-giay',1),
  ('dong-nai-thong-nhat','Bàu Hàm 2','dong-nai-thong-nhat-bau-ham-2',2),
  ('dong-nai-thong-nhat','Gia Tân 1','dong-nai-thong-nhat-gia-tan-1',3),
  ('dong-nai-thong-nhat','Gia Tân 2','dong-nai-thong-nhat-gia-tan-2',4),
  ('dong-nai-thong-nhat','Gia Tân 3','dong-nai-thong-nhat-gia-tan-3',5),
  ('dong-nai-thong-nhat','Gia Kiệm','dong-nai-thong-nhat-gia-kiem',6),
  ('dong-nai-thong-nhat','Hưng Lộc','dong-nai-thong-nhat-hung-loc',7),
  ('dong-nai-thong-nhat','Lộ 25','dong-nai-thong-nhat-lo-25',8),
  ('dong-nai-thong-nhat','Quang Trung','dong-nai-thong-nhat-quang-trung',9),
  ('dong-nai-thong-nhat','Xuân Thiện','dong-nai-thong-nhat-xuan-thien',10),
  ('dong-nai-trang-bom','Trảng Bom','dong-nai-trang-bom-trang-bom',1),
  ('dong-nai-trang-bom','An Viễn','dong-nai-trang-bom-an-vien',2),
  ('dong-nai-trang-bom','Bàu Hàm','dong-nai-trang-bom-bau-ham',3),
  ('dong-nai-trang-bom','Bình Minh','dong-nai-trang-bom-binh-minh',4),
  ('dong-nai-trang-bom','Cây Gáo','dong-nai-trang-bom-cay-gao',5),
  ('dong-nai-trang-bom','Đông Hòa','dong-nai-trang-bom-dong-hoa',6),
  ('dong-nai-trang-bom','Đồi 61','dong-nai-trang-bom-doi-61',7),
  ('dong-nai-trang-bom','Giang Điền','dong-nai-trang-bom-giang-dien',8),
  ('dong-nai-trang-bom','Hố Nai 3','dong-nai-trang-bom-ho-nai-3',9),
  ('dong-nai-trang-bom','Hưng Thịnh','dong-nai-trang-bom-hung-thinh',10),
  ('dong-nai-trang-bom','Quảng Tiến','dong-nai-trang-bom-quang-tien',11),
  ('dong-nai-trang-bom','Sông Thao','dong-nai-trang-bom-song-thao',12),
  ('dong-nai-trang-bom','Sông Trầu','dong-nai-trang-bom-song-trau',13),
  ('dong-nai-trang-bom','Tây Hòa','dong-nai-trang-bom-tay-hoa',14),
  ('dong-nai-trang-bom','Thanh Bình','dong-nai-trang-bom-thanh-binh',15),
  ('dong-nai-trang-bom','Trung Hòa','dong-nai-trang-bom-trung-hoa',16),
  ('dong-nai-vinh-cuu','Vĩnh An','dong-nai-vinh-cuu-vinh-an',1),
  ('dong-nai-vinh-cuu','Bình Hòa','dong-nai-vinh-cuu-binh-hoa',2),
  ('dong-nai-vinh-cuu','Bình Lợi','dong-nai-vinh-cuu-binh-loi',3),
  ('dong-nai-vinh-cuu','Hiếu Liêm','dong-nai-vinh-cuu-hieu-liem',4),
  ('dong-nai-vinh-cuu','Mã Đà','dong-nai-vinh-cuu-ma-da',5),
  ('dong-nai-vinh-cuu','Phú Lý','dong-nai-vinh-cuu-phu-ly',6),
  ('dong-nai-vinh-cuu','Tân An','dong-nai-vinh-cuu-tan-an',7),
  ('dong-nai-vinh-cuu','Tân Bình','dong-nai-vinh-cuu-tan-binh',8),
  ('dong-nai-vinh-cuu','Thạnh Phú','dong-nai-vinh-cuu-thanh-phu',9),
  ('dong-nai-vinh-cuu','Thiện Tân','dong-nai-vinh-cuu-thien-tan',10),
  ('dong-nai-vinh-cuu','Trị An','dong-nai-vinh-cuu-tri-an',11),
  ('dong-nai-vinh-cuu','Vĩnh Tân','dong-nai-vinh-cuu-vinh-tan',12),
  ('dong-nai-xuan-loc','Gia Ray','dong-nai-xuan-loc-gia-ray',1),
  ('dong-nai-xuan-loc','Bảo Hòa','dong-nai-xuan-loc-bao-hoa',2),
  ('dong-nai-xuan-loc','Lang Minh','dong-nai-xuan-loc-lang-minh',3),
  ('dong-nai-xuan-loc','Suối Cao','dong-nai-xuan-loc-suoi-cao',4),
  ('dong-nai-xuan-loc','Suối Cát','dong-nai-xuan-loc-suoi-cat',5),
  ('dong-nai-xuan-loc','Xuân Bắc','dong-nai-xuan-loc-xuan-bac',6),
  ('dong-nai-xuan-loc','Xuân Định','dong-nai-xuan-loc-xuan-dinh',7),
  ('dong-nai-xuan-loc','Xuân Hiệp','dong-nai-xuan-loc-xuan-hiep',8),
  ('dong-nai-xuan-loc','Xuân Hòa','dong-nai-xuan-loc-xuan-hoa',9),
  ('dong-nai-xuan-loc','Xuân Hưng','dong-nai-xuan-loc-xuan-hung',10),
  ('dong-nai-xuan-loc','Xuân Phú','dong-nai-xuan-loc-xuan-phu',11),
  ('dong-nai-xuan-loc','Xuân Tâm','dong-nai-xuan-loc-xuan-tam',12),
  ('dong-nai-xuan-loc','Xuân Thành','dong-nai-xuan-loc-xuan-thanh',13),
  ('dong-nai-xuan-loc','Xuân Thọ','dong-nai-xuan-loc-xuan-tho',14),
  ('dong-nai-xuan-loc','Xuân Trường','dong-nai-xuan-loc-xuan-truong',15)
) AS v(district_slug, name, slug, ord) ON d.slug = v.district_slug;

NOTIFY pgrst, 'reload schema';
